language: rust
os:
    - linux
script:
    - cargo build
    - cargo test
before_script:
    - curl https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
    - echo "deb http://apt.mopidy.com/ stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
    - echo "deb-src http://apt.mopidy.com/ stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y libspotify12 libspotify-dev
